name: tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [ 7.3 ]
        laravel: [ '5.5' ]
    name: P${{ matrix.php }} - L${{ matrix.laravel }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.2
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.composer/cache/files
          key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: xdebug
      - name: Install dependencies
        run: composer install --prefer-dist --no-interaction
      - name: Prepare database and configuration
        run: |
          touch database/database.sqlite
          cp .env.example .env
          php artisan key:generate
          php artisan migrate
          php artisan passport:install
          php artisan db:seed
      - name: Execute PHPUnit tests
        run: vendor/bin/phpunit --verbose --coverage-text
      - name: Execute Cypress tests
        uses: cypress-io/github-action@v2
        with:
          working-directory: front-end
          start: php ../artisan serve, yarn serve
          wait-on: 'http://127.0.0.1:8000, http://127.0.0.1:8080'
